planilla: variables_BBVA.xlsx
mensajes:
  0:
    texto: Hola! Soy Mora, el asistente virtual de CDN. ¿Me dirías tu número de DNI?
    siguientes:
      funcion: verificar_dni
      resultados:
        False: 1
        True: 3
  1:
    texto: Hoy no tenemos asignada deuda con tu número de DNI. Indicanos por favor el número de DNI DEL TITULAR DE LA CUENTA
    siguientes:
      funcion: verificar_dni
      resultados:
        False: 2
        True: 3
  2:
    texto: Al momento en CDN no tenemos asignada tu deuda, por favor contactate con BBVA al 0800-999-2282 DE LUNES A VIERNES DE 10 A 15 HS
    siguientes:
      funcion: fin
      resultados:
        fin: 18
  3:
    texto: "{0} Un gusto saludarte! Te pedimos que nos facilites un correo electrónico para continuar la gestión"
    funcion: dame_nombre
    siguientes:
      funcion: verificar_correo
      resultados:
        True: 4
        False: 3
  4:
    texto: >
        "
        Muchas gracias! Te contamos que a la fecha estás en mora por un importe de {0}. Para poder ayudarte, decime el motivo de tu contacto
        1) Ya pague
        2) Quiero conocer mis opciones de pago
        3) Libre deuda
        4) Defensa del consumidor
        5) Desconozco deuda/No tengo deuda con BBVA
        "
    funcion: dame_deuda
    siguientes:
      funcion: "lambda x: x"
      resultados:
        1: 5
        2: 6
        3: 7
        4: 8
        5: 9
  5:
    texto: "Perfecto, te pedimos que nos indiques la fecha de pago ej: 01/03/2024. Y nos envíes el archivo adjunto del comprobante para poder registrarlo"
    siguientes:
      funcion: verificar_mes_actual
      True: 10
      False: 5
  6:
    texto: >
      "
      Perfecto, hoy tenemos una oferta única para vos, con una quita extraordinaria, cancelas por {0}. ¿Ves factible abonar esto al {1}?
      1) SI
      2) NO
      "
    funcion: dame_oferta_fecha
    siguientes:
      funcion: "lambda x: x"
      resultados:
        1: 11
        2: 12
  7:
    texto: Para solicitar el libre deuda podes acercarte a la sucursal más cercana o comunicarse al 0800-999-2282 de lunes a viernes de 10 a 15 hs. Muchas gracias
    siguientes:
      funcion: fin
      resultados:
        fin: 18
  8:
    texto: estimado/a te va a estar llamando a la brevedad el asesor designado a tu legajo en el horario de 9 a 17 hs. Saludos!
    siguientes:
      funcion: fin
      resultados:
        fin: 18
  9:
    texto: Como desconoces la deuda, en breves un asesor se comunicará y te dará más detalles. Recordá que nuestro horario de atención es de lunes a viernes de 9 a 20 h y te podes contactar con nosotros al 0800 220 0059. Muchas gracias
    siguientes:
      funcion: fin
      resultados:
        fin: 18
  10:
    texto: Muchas gracias por enviarnos el comprobante de pago, en las proximas 48 hs impactará en su cuenta
    siguientes:
      funcion: fin
      resultados:
        fin: 18
  11:
    texto: >
      "
      Perfecto, entonces el pago deberá realizarse antes de {0}. ¿Confirma?
      1) SI
      2) NO
      "
    funcion: dame_fecha_limite
    siguientes:
      funcion: "lambda x: x"
      resultados:
        1: 13
        2: 14
  12:
    texto: >
      "
      Desconocemos la situación de cada uno, pero queremos ayudarte a no tener este problema. Tu cuenta está a punto de ser derivada a la etapa siguiente, la de un fideicomiso, lo que implica costes y honorarios por la operación. Podemos ofrecerte un plan de pagos CON HASTA 50 % OFF. Abonando hoy cancelás tu deuda por {0}.
      Ves factible abonar este estado?
      1) SI
      2) NO
      "
    funcion: dame_deuda
    siguientes:
      funcion: "lambda x: x"
      resultados:
        1: 11
        2: 15
  18:
    texto: Conversación terminada
