planilla: variables_BBVA.xlsx
mensajes:
  0:
    texto: Hola! Soy Mora, el asistente virtual de CDN. ¿Me dirías tu número de DNI?
    siguientes:
      funcion: verificar_dni
      resultados:
        False: 1
        True: 3
  1:
    texto: Hoy no tenemos asignada deuda con tu número de DNI. Indicanos por favor el número de DNI DEL TITULAR DE LA CUENTA
    siguientes:
      funcion: verificar_dni
      resultados:
        False: 2
        True: 3
  2:
    texto: Al momento en CDN no tenemos asignada tu deuda, por favor contactate con BBVA al 0800-999-2282 DE LUNES A VIERNES DE 10 A 15 HS
    siguientes:
      funcion: fin
      resultados:
        fin: 18
  3:
    texto: "{0} Un gusto saludarte! Te pedimos que nos facilites un correo electrónico para continuar la gestión"
    funcion: dame_nombre
    siguientes:
      funcion: verificar_correo
      resultados:
        True: 4
        False: 3
  4:
    texto: >
        "
        Muchas gracias! Te contamos que a la fecha estás en mora por un importe de {0}. Para poder ayudarte, decime el motivo de tu contacto
        1) Ya pague
        2) Quiero conocer mis opciones de pago
        3) Libre deuda
        4) Defensa del consumidor
        5) Desconozco deuda/No tengo deuda con BBVA
        "
    funcion: dame_deuda
    siguientes:
      funcion: "lambda x: x"
      resultados:
        1: 5
        2: 6
        3: 7
        4: 8
        5: 9
  5:
    texto: "Perfecto, te pedimos que nos indiques la fecha de pago ej: 01/03/2024. Y nos envíes el archivo adjunto del comprobante para poder registrarlo"
    funcion: verificar_mes_actual
    siguientes:
      True: 10
      False: 5
  18:
    texto: Conversación terminada
