planilla: variables_BBVA.xlsx
mensajes:
  0:
    texto: Hola! Soy Mora, el asistente virtual de CDN. ¿Me dirías tu número de DNI?
    siguientes:
      funcion: verificar_dni
      resultados:
        False: 1
        True: 3
  1:
    texto: Hoy no tenemos asignada deuda con tu número de DNI. Indicanos por favor el número de DNI del TITULAR De LA CUeNTA
    siguientes:
      funcion: verificar_dni
      resultados:
        False: 2
        True: 3
  2:
    texto: Al momento en CDN no tenemos asignada tu deuda, por favor contactate con BBVA al 0800-999-2282 De LUNeS A VieRNeS de 10 a 15 hs
    siguientes:
      funcion: fin
      resultados:
        fin: 18

  18:
    texto: Conversación terminada
